[auth]
credentials = '{"usernames": {"demo": {"name": "Demo User", "hashed_password": "$2b$12$4Q1z3j2K8mL9nP0qR1sT2uV3wX4yZ5aB6cD7eF8gH9iJ0kL1mN2oP3"}, "customer1": {"name": "Customer 1", "password": "pass123"}}}'
cookie = '{"name": "smart_kitchen", "key": "random_key_2025", "expiry_days": 30}'
preauthorized = null